# -*- coding: utf-8 -*-
"""MovieRecommendationModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oDXh-LtfWDVGdz3b6bnng58sU46cmrgV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ast

df_credits=pd.read_csv("/content/tmdb_5000_credits.csv")
df_movies=pd.read_csv("/content/movies.csv")

df_credits.head(1)
df_movies.head(1)

df_movies=df_movies.merge(df_credits,on="title")

df_movies.shape

df_credits.shape

df_movies.head(1)

#title
#original_language
#movie_id
#cast
#crew

df_movies["original_language"].value_counts()

df_movies.info()

df_movies = df_movies[['movie_id','title','original_language','cast','crew']]

df_movies.head()

df_movies.isnull().sum()

df_movies.duplicated().sum()

df_movies = df_movies.drop_duplicates()

df_movies.duplicated().sum()

df_movies["cast"][0]

def converter(obj):
  L=[]
  counter=0
  for i in ast.literal_eval(obj):
    if counter!=3:
      L.append(i["name"])
      counter+=1
    else:
      break
  return L

df_movies["cast"]=df_movies["cast"].apply(converter)

def fetch_director(obj):
  L=[]
  for i in ast.literal_eval(obj):
    if i["job"]=="Director":
      L.append(i["name"])
      break
  return L

df_movies["crew"]=df_movies["crew"].apply(fetch_director)

df_movies.head()

df_movies.head()

df_movies["cast"]= df_movies["cast"].apply(lambda x:[i.replace(" "," ") for i in x])
df_movies["crew"]= df_movies["crew"].apply(lambda x:[i.replace(" "," ") for i in x])

df_movies.head()

new_df = df_movies[["movie_id",'title']]
new_df

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

vector = cv.fit_transform(new_df_df['title']).toarray()
vector.shape

from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)
similarity
new_df[new_df['title'] == 'The Lego Movie'].index[0]
def recommend(movie):
    index = new_df[new_df['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new_df.iloc[i[0]].title)

vector = cv.fit_transform(new_df['title']).toarray()
vector.shape
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)
similarity
new_df[new_df['title'] == 'The Lego Movie'].index[0]
def recommend(movie):
    index = new_df[new_df['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new_df.iloc[i[0]].title)
recommend("Gandhi")
import pickle
pickle.dump(new_df,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

recommend("Avatar")